### ISSUE TITLE
Run project at unity

### ISSUE THREAD

**Issue by kss943** [oviebd/Unitty-SwiftCommunication#2]
Hello
Is it possible to run this project at Unity?
After starting an error in the console appears:
```
EntryPointNotFoundException: _addTwoNumberInIOS
PluginHelper.AddTwoNumber () (at Assets/PluginHelper.cs:20)
PluginHelper.Start () (at Assets/PluginHelper.cs:15)
```

Unity version: 2019.3.11f1

**Comment by StanisalvPopadynets** [comment]
I ecnountered the same problem. Unable to run in Unity.
